spring:
# Database properties
  datasource:
    url: jdbc:oracle:thin:@151.24.124.111:1521/pdb1.bip.lan
    username: NGFA
    password: Password1
# JPA Hibernate properties
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

# Server properties
spring.application.name: gfa-anagrafiche
api.name: api
      
server:
  port: 8081
  servlet:
    context-path: /anagrafiche/ente
