db:
  host: 151.24.113.197
  port: 1521
  
spring.jackson.default-property-inclusion: NON_NULL
  
spring:
# Database properties
  datasource:
    url: jdbc:oracle:thin:@${db.host}:${db.port}/pdb1.bip.lan
    username: NGFA
    password: Password1
# JPA Hibernate properties
  jpa:
    hibernate:
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

# Microservice properties
spring.application.name: gfa-anagrafiche

api-tag: api
path-name:
  ente: ente
  regione: regione
      
server:
  port: 8081
  servlet:
    context-path: /anagrafiche
