server:
  port: 9090

uri.test: http://127.0.0.1:8081

spring:
  application:
    name: gfa-gateway
  cloud:
    gateway:
      routes:
        - id: TEST-SERVICES
          uri: ${uri.test}
          predicates:
            - Path=/anagrafiche/**
          filters:
            - name: CircuitBreaker
              args:
                name: GfaCircuitBreaker
                fallbackuri: forward:/testFallBack
                
resilience4j.timelimiter:
    instances:
        GfaCircuitBreaker:
            timeoutDuration: 8s
            cancelRunningFuture: true
           
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
#        cloud:
#          gateway:
#            filter:
#              factory: TRACE