server:
  port: 9090

uri:
  anagrafiche: http://127.0.0.1:8081
  file-manager: http://127.0.0.1:8083

spring:
  application:
    name: gfa-gateway
  cloud:
    gateway:
      routes:
        - id: GFA-ANAGRAFICHE
          uri: ${uri.anagrafiche}
          predicates:
            - Path=/anagrafiche/**
          filters:
            - name: CircuitBreaker
              args:
                name: GfaCircuitBreaker
                fallbackuri: forward:/testFallBack
        - id: GFA-FILE-MANAGER
          uri: ${uri.file-manager}
          predicates:
            - Path=/file-manager/**
          filters:
            - name: CircuitBreaker
              args:
                name: GfaCircuitBreaker
                fallbackuri: forward:/testFallBack
                
resilience4j.timelimiter:
    instances:
        GfaCircuitBreaker:
            timeoutDuration: 15s
            cancelRunningFuture: true
           
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
#        cloud:
#          gateway:
#            filter:
#              factory: TRACE