server.port: 8082
pod.name: NOME_POD_TEST_SVIL  
spring.application.name: gfa-gestionale
gateway.host: "http://127.0.0.1:9090"

joinfaces:
  jsf:
    PROJECT_STAGE: Production
    FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: vela
tomcat:
  version: "@tomcat.version@"
jetty:
  version: "@jetty.version@"
undertow:
  version: "@undertow.version@"
application-users:
  users-credentials:
    - username: persapiens
      password: 123
      authorities: ROLE_ADMIN
    - username: nyilmaz
      password: qwe
      authorities: ROLE_USER
      
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: TRACE
#        cloud:
#          kubernetes: DEBUG

#db:
#  host: 151.24.113.197
#  port: 1521
#
#spring:
## Database properties
#  datasource:
#    url: jdbc:oracle:thin:@${db.host}:${db.port}/pdb1.bip.lan
#    username: NGFA
#    password: Password1
#    type: oracle.ucp.jdbc.PoolDataSource
#    oracleucp.min-pool-size: 1
#    oracleucp.max-pool-size: 5
#
#spring.session.store-type: jdbc
#server.servlet.session.timeout: -1 # Session timeout. If a duration suffix is not specified, seconds are used.
#spring.session.jdbc.initialize-schema: always # Database schema initialization mode.
#spring.session.jdbc.schema: classpath:org/springframework/session/jdbc/schema-session.sql # Path to the SQL file to use to initialize the database schema.
#spring.session.jdbc.table-name: SPRING_SESSION # Name of the database table used to store sessions.